### ISSUE TITLE
Command starting with space crashes with UnboundLocalError

### ISSUE THREAD

**Issue by ivanistheone** [sympy/sympy-live#102]
Entering ` 2+2` (2+2 prefixed by a space) results in:

```
Exception in SymPy Live of type  <type 'exceptions.UnboundLocalError'>
for reference the last 5 stack trace entries are
Traceback (most recent call last):
  File "/b/d/h/a/s~sympy-live-hrd/46.39/shell.py", line 774, in post
    live.evaluate(statement, session, printer, stream)
  File "/b/d/h/a/s~sympy-live-hrd/46.39/shell.py", line 341, in evaluate
    return self.error(stream, self.syntaxerror())
  File "/b/d/h/a/s~sympy-live-hrd/46.39/shell.py", line 252, in syntaxerror
    return ''.join(text), line
UnboundLocalError: local variable 'line' referenced before assignment
```

**Comment by ivanistheone** [comment]
BTW, I'm looking into this and will try to fix on my own. Would really like to get to know sympy live better. I've been using it so much lately that I feel the need to contribute somehow. The most amazing software every for teaching math.

@lidavidm Tips for where to look would be appreciated though...

**Comment by lidavidm** [comment]
https://github.com/sympy/sympy-live/blob/master/shell.py#L233

Looks like the 'else' and 'except' branches of that try-except don't make sure to define 'line' (which I think is the line number of the exception). Maybe look if there's a better way of getting that info from the exception. That's not the root cause though, it's an error when trying to format the underlying exception.

**Comment by lidavidm** [comment]
Feel free to ask me any questions you have on Live. I haven't looked at this much since I went to college and it would be nice to see it maintained still. Someday WebAssembly will be good enough to ship a Python interpreter in the browser...

**Comment by ivanistheone** [comment]
Okay so touched the error handling a bit:
https://github.com/minireference/sympy-live/commit/a77f403661ca82accc7c5697043ce11d5939a5ac

Now I see the actual error:
```
>>>  2+2
Traceback (most recent call last):
  File "<string>", line 1
    2+2
    ^
IndentationError: unexpected indent
```

Will look into `ast.parse` later today or tomorrow.

**Comment by ivanistheone** [comment]
One possible fix would be for single-line inputs to get `lstrip`ped before passing them to `ast.parse`.

**Comment by lidavidm** [comment]
That would be nice just for convenience, though in general if they make a syntactic error we want to report that (Live is supposed to emulate a Python REPL).
