### ISSUE TITLE
Is there a way to link few lines of code to be executed on sympy live?

### ISSUE THREAD

**Issue by ananthp** [sympy/sympy-live#118]
I would like to share a code snippet to be executed on sympy live. I can share the code directly and ask the receiver to open sympy live and copy-paste it to see the result. Alternatively, is there a way to just send a link which opens sympy live and executes the attached code snippet?

I'm aware that I can run a query in sympy gamma and share it. But I need to share a few lines of actual sympy code that need to be executed in a consistent manner.

**Comment by ylemkimon** [comment]
You can do http://live.sympy.org/?evaluate=[code]. Of course, it has to be url-encoded. Also, in the SymPy live, there is a pin button where you can generate a link based on your history.

**Comment by ananthp** [comment]
Pin button does it! Thanks @ylemkimon
