### ISSUE TITLE
Error in doc

### ISSUE THREAD

**Issue by PierreMarchand20** [sympy/sympy-live#133]
I just discovered this module and I was starting to do the introduction but I got in error in the live shell on the website:
<img width="605" alt="image" src="https://user-images.githubusercontent.com/15056323/50347590-54c3c600-0536-11e9-91a5-1899f12c6b04.png">

It is at the end of https://docs.sympy.org/latest/tutorial/intro.html#a-more-interesting-example

**Comment by PierreMarchand20** [comment]
Well I just followed the tutorial. But then I cleaned the kernel just to make the picture I sent you previously.

I would not know how to define them as non-commutative anyway ahah

**Comment by ivanistheone** [comment]
@PierreMarchand20 Could you try running the examples above again?

It's possible it was a transient/temporary error and it works now (seen others like this). If so, please close the issue.

**Comment by PierreMarchand20** [comment]
It seems to work now.
