### ISSUE TITLE
New Voice Commands Feature in Sympy-live

### ISSUE THREAD

**Issue by Adarshg315** [sympy/sympy-live#145]
I was thinking of implementing a **voice based commands**  in the feed section as it is difficult to type the expressions, we can use some speech API for that sake
is it good to work on please tell me

**Comment by asmeurer** [comment]
This seems like a very difficult problem. Even if you have a good speech-to-text library, you still need to process the text. So this problem is a least as hard as natural language processing, which we don't support yet either.
